import { describe, it, expect } from 'vitest'
import { mount } from '@vue/test-utils'
import Checkbox from './Checkbox.vue'

describe('Checkbox', () => {
  it('renders with data-rig-checkbox', () => {
    const wrapper = mount(Checkbox)
    expect(wrapper.attributes('data-rig-checkbox')).toBe('')
  })

  it('reflects checked state via data attribute', () => {
    const wrapper = mount(Checkbox, { props: { modelValue: true } })
    expect(wrapper.attributes('data-state')).toBe('checked')
  })

  it('emits update:modelValue on change', async () => {
    const wrapper = mount(Checkbox, { props: { modelValue: false } })
    await wrapper.find('input').setValue(true)
    expect(wrapper.emitted('update:modelValue')?.[0]).toEqual([true])
  })

  it('handles disabled state', () => {
    const wrapper = mount(Checkbox, { props: { disabled: true } })
    expect(wrapper.attributes('data-disabled')).not.toBeUndefined()
    expect(wrapper.find('input').attributes('disabled')).toBe('')
  })

  it('supports indeterminate state', () => {
    const wrapper = mount(Checkbox, { props: { indeterminate: true } })
    expect(wrapper.attributes('data-indeterminate')).not.toBeUndefined()
  })

  it('toggles value on Space key via native input', async () => {
    const wrapper = mount(Checkbox, { attachTo: document.body })
    const input = wrapper.find('input[type="checkbox"]')
    await input.setValue(true)
    expect(wrapper.emitted('update:modelValue')?.[0]).toEqual([true])
    wrapper.unmount()
  })

  it('focuses the checkbox input element', async () => {
    const wrapper = mount(Checkbox, { attachTo: document.body })
    const input = wrapper.find('input[type="checkbox"]')
    ;(input.element as HTMLInputElement).focus()
    expect(document.activeElement).toBe(input.element)
    wrapper.unmount()
  })
})

// ── Interaction test coverage ────────────────────────────────────────────────
// Generated by fill-interaction-gaps.mjs to close health-score gaps.

describe('Checkbox interactions', () => {
  it('responds to keyboard events', async () => {
    const wrapper = mount(Checkbox, {
      props: { modelValue: false },
      attachTo: document.body,
    })
    const el = wrapper.find('[tabindex], input, button, [role]')
    const target = el.exists() ? el : wrapper
    await target.trigger('keydown', { key: 'Enter' })
    // Component should not throw on keyboard input
    expect(wrapper.html()).toBeTruthy()
    await target.trigger('keydown', { key: 'Escape' })
    expect(wrapper.html()).toContain('<')
    wrapper.unmount()
  })
})
