import { describe, it, expect } from 'vitest'
import { mount } from '@vue/test-utils'
import Divider from './Divider.vue'

describe('Divider', () => {
  it('renders with data-rig-divider and role separator', () => {
    const wrapper = mount(Divider)
    expect(wrapper.attributes('data-rig-divider')).toBe('')
    expect(wrapper.attributes('role')).toBe('separator')
  })

  it('defaults to horizontal orientation', () => {
    const wrapper = mount(Divider)
    expect(wrapper.attributes('aria-orientation')).toBe('horizontal')
    expect(wrapper.attributes('data-vertical')).toBeUndefined()
  })

  it('supports vertical orientation', () => {
    const wrapper = mount(Divider, { props: { vertical: true } })
    expect(wrapper.attributes('aria-orientation')).toBe('vertical')
    expect(wrapper.attributes('data-vertical')).not.toBeUndefined()
  })

  it('renders label text', () => {
    const wrapper = mount(Divider, { props: { label: 'OR' } })
    expect(wrapper.find('[data-rig-divider-label]').text()).toBe('OR')
  })

  it('renders slot content as label', () => {
    const wrapper = mount(Divider, { slots: { default: 'Section' } })
    expect(wrapper.find('[data-rig-divider-label]').text()).toBe('Section')
  })

  it('hides label span when no label or slot', () => {
    const wrapper = mount(Divider)
    expect(wrapper.find('[data-rig-divider-label]').exists()).toBe(false)
  })

  it('ignores keyboard events (non-interactive)', async () => {
    const wrapper = mount(Divider)
    await wrapper.trigger('keydown', { key: 'Escape' })
    expect(wrapper.emitted('click')).toBeUndefined()
  })

  it('has separator role', () => {
    const wrapper = mount(Divider)
    expect(wrapper.attributes('role')).toBe('separator')
  })

  it('renders label when label prop is set', () => {
    const wrapper = mount(Divider, { props: { label: 'or' } })
    expect(wrapper.find('[data-rig-divider-label]').text()).toBe('or')
  })

  it('updates aria-orientation when vertical changes', async () => {
    const wrapper = mount(Divider)
    await wrapper.setProps({ vertical: true })
    expect(wrapper.attributes('aria-orientation')).toBe('vertical')
  })
})

// ── Interaction test coverage ────────────────────────────────────────────────
// Generated by fill-interaction-gaps.mjs to close health-score gaps.

describe('Divider interactions', () => {
  it('is not focusable (decorative separator)', () => {
    const wrapper = mount(Divider, {
      attachTo: document.body,
    })
    // A decorative separator should not have tabindex
    expect(wrapper.attributes('tabindex')).toBeUndefined()
    // Attempting focus should not move activeElement to the divider
    ;(wrapper.element as HTMLElement).focus()
    expect(document.activeElement).not.toBe(wrapper.element)
    wrapper.unmount()
  })
})
