export { default as IdeShell } from './IdeShell.vue'
export { default as ChatPanel } from './ChatPanel.vue'
export { default as SearchPanel } from './SearchPanel.vue'
export { default as FileBrowser } from './FileBrowser.vue'
export { default as ContentViewer } from './ContentViewer.vue'
export { default as FormView } from './FormView.vue'
export { default as WelcomeView } from './WelcomeView.vue'
export { default as SettingsView } from './SettingsView.vue'
export { useShellState } from './useShellState'
export { ShellKey } from './types'
export type { ShellState, ShellConfig, PanelDescriptor, ActivityView } from './types'
export type { ChatMessage } from './ChatPanel.vue'
export type { StatItem } from './WelcomeView.vue'
