// Web — Marketing site components and composables
export { default as SiteShell } from './SiteShell.vue'
export { default as SiteNav } from './SiteNav.vue'
export type { NavItem } from './SiteNav.vue'
export { default as Hero } from './Hero.vue'
export { default as Section } from './Section.vue'
export { default as StatRow } from './StatRow.vue'
export type { WebStatItem } from './StatRow.vue'
export { default as CTABanner } from './CTABanner.vue'
export { default as Testimonial } from './Testimonial.vue'
export { default as PricingCard } from './PricingCard.vue'
export { default as SiteFooter } from './SiteFooter.vue'
export { useHashRouter } from './useHashRouter'
export type { UseHashRouterOptions } from './useHashRouter'
export { useScrollNav } from './useScrollNav'
export type { UseScrollNavOptions } from './useScrollNav'
export { default as SectionDivider } from './SectionDivider.vue'
export { default as FlankedHeading } from './FlankedHeading.vue'
export { default as Ornament } from './Ornament.vue'
export { default as ContactForm } from './ContactForm.vue'
export type { ContactFormField } from './ContactForm.vue'
export { default as NewsletterForm } from './NewsletterForm.vue'
export { default as ServiceGrid } from './ServiceGrid.vue'
export type { ServiceItem } from './ServiceGrid.vue'
export { default as TeamGrid } from './TeamGrid.vue'
export type { TeamMember } from './TeamGrid.vue'
export { default as MenuList } from './MenuList.vue'
export type { MenuItem } from './MenuList.vue'
export { default as FeatureList } from './FeatureList.vue'
export type { FeatureItem } from './FeatureList.vue'
export { default as Gallery } from './Gallery.vue'
export type { GalleryItem } from './Gallery.vue'
export { default as MapPlaceholder } from './MapPlaceholder.vue'
export { useDetailView } from './useDetailView'
export type { UseDetailViewOptions, UseDetailViewReturn } from './useDetailView'
