import { describe, it, expect } from 'vitest'
import { mount } from '@vue/test-utils'
import ColorPicker from './ColorPicker.vue'

describe('ColorPicker', () => {
  it('renders with data-rig-color-picker', () => {
    const wrapper = mount(ColorPicker)
    expect(wrapper.attributes('data-rig-color-picker')).toBeDefined()
  })

  it('shows color preview', () => {
    const wrapper = mount(ColorPicker, { props: { modelValue: '#ff0000' } })
    expect(wrapper.find('[data-rig-color-picker-preview]').exists()).toBe(true)
  })

  it('renders HSL sliders', () => {
    const wrapper = mount(ColorPicker)
    expect(wrapper.find('[data-rig-color-picker-hue]').exists()).toBe(true)
    expect(wrapper.find('[data-rig-color-picker-saturation]').exists()).toBe(true)
    expect(wrapper.find('[data-rig-color-picker-lightness]').exists()).toBe(true)
  })

  it('renders hex input', () => {
    const wrapper = mount(ColorPicker)
    expect(wrapper.find('[data-rig-color-picker-input]').exists()).toBe(true)
  })

  it('emits update on hex input', async () => {
    const wrapper = mount(ColorPicker)
    const input = wrapper.find('[data-rig-color-picker-input]')
    await input.setValue('#00ff00')
    await input.trigger('input')
    expect(wrapper.emitted('update:modelValue')).toBeTruthy()
  })

  it('has accessible labels', () => {
    const wrapper = mount(ColorPicker)
    expect(wrapper.find('[aria-label="Hue"]').exists()).toBe(true)
    expect(wrapper.find('[aria-label="Saturation"]').exists()).toBe(true)
    expect(wrapper.find('[aria-label="Lightness"]').exists()).toBe(true)
  })

  it('emits update on hue slider change', async () => {
    const wrapper = mount(ColorPicker, { props: { modelValue: '#c9956d' } })
    const hueSlider = wrapper.find('[data-rig-color-picker-hue]')
    await hueSlider.setValue('180')
    const emitted = wrapper.emitted('update:modelValue')
    expect(emitted).toBeTruthy()
    expect(emitted![emitted!.length - 1]![0]).toMatch(/^#[0-9a-f]{6}$/)
  })

  it('supports focus management', async () => {
    const wrapper = mount(ColorPicker, {
      props: { modelValue: '#c9956d' },
      attachTo: document.body,
    })
    const hueSlider = wrapper.find('[data-rig-color-picker-hue]').element as HTMLElement
    hueSlider.focus()
    expect(document.activeElement).toBe(hueSlider)
    wrapper.unmount()
  })
})

// ── Interaction test coverage ────────────────────────────────────────────────
// Generated by fill-interaction-gaps.mjs to close health-score gaps.

describe('ColorPicker interactions', () => {
  it('responds to keyboard events', async () => {
    const wrapper = mount(ColorPicker, {
      props: { modelValue: '#ff0000' }, attachTo: document.body,
    })
    const el = wrapper.find('[tabindex], input, button, [role]')
    const target = el.exists() ? el : wrapper
    await target.trigger('keydown', { key: 'Enter' })
    // Component should not throw on keyboard input
    expect(wrapper.html()).toBeTruthy()
    await target.trigger('keydown', { key: 'Escape' })
    expect(wrapper.html()).toContain('<')
    wrapper.unmount()
  })
})

