import { describe, it, expect } from 'vitest'
import { mount } from '@vue/test-utils'
import ShellGrid from './ShellGrid.vue'

describe('ShellGrid', () => {
  it('renders with data-rig-shell-grid', () => {
    const wrapper = mount(ShellGrid)
    expect(wrapper.attributes('data-rig-shell-grid')).toBeDefined()
  })

  it('renders all named areas', () => {
    const wrapper = mount(ShellGrid, {
      slots: {
        activity: '<div id="act">Activity</div>',
        sidebar: '<div id="side">Sidebar</div>',
        editor: '<div id="edit">Editor</div>',
        panel: '<div id="pan">Panel</div>',
        statusbar: '<div id="stat">Status</div>',
      },
    })
    expect(wrapper.find('#act').exists()).toBe(true)
    expect(wrapper.find('#side').exists()).toBe(true)
    expect(wrapper.find('#edit').exists()).toBe(true)
    expect(wrapper.find('#pan').exists()).toBe(true)
    expect(wrapper.find('#stat').exists()).toBe(true)
  })

  it('sets direction data attribute', () => {
    const wrapper = mount(ShellGrid, { props: { direction: 'rtl' } })
    expect(wrapper.attributes('data-direction')).toBe('rtl')
  })

  it('applies sidebar width from sizes', () => {
    const wrapper = mount(ShellGrid, {
      props: { sizes: { sideWidth: 300, panelHeight: 150 } },
    })
    const sidebar = wrapper.find('[data-rig-shell-sidebar]')
    expect(sidebar.attributes('style')).toContain('width: 300px')
  })

  it('applies panel height from sizes', () => {
    const wrapper = mount(ShellGrid, {
      props: { sizes: { sideWidth: 260, panelHeight: 250 } },
    })
    const panel = wrapper.find('[data-rig-shell-panel]')
    expect(panel.attributes('style')).toContain('height: 250px')
  })

  it('renders resizers when resizable', () => {
    const wrapper = mount(ShellGrid, { props: { resizable: true } })
    expect(wrapper.findAll('[data-rig-resizer]').length).toBe(2)
  })

  it('hides resizers when not resizable', () => {
    const wrapper = mount(ShellGrid, { props: { resizable: false } })
    expect(wrapper.findAll('[data-rig-resizer]').length).toBe(0)
  })

  it('has tabindex="-1" for programmatic focus', () => {
    const wrapper = mount(ShellGrid)
    expect(wrapper.attributes('tabindex')).toBe('-1')
  })

  it('can receive programmatic focus', () => {
    const wrapper = mount(ShellGrid, { attachTo: document.body })
    wrapper.element.focus()
    expect(document.activeElement).toBe(wrapper.element)
    wrapper.unmount()
  })

  it('has aria-label on the root element', () => {
    const wrapper = mount(ShellGrid)
    expect(wrapper.attributes('aria-label')).toBe('Application shell')
  })

  it('updates direction data attribute on prop change', async () => {
    const wrapper = mount(ShellGrid, { props: { direction: 'ltr' } })
    expect(wrapper.attributes('data-direction')).toBe('ltr')
    await wrapper.setProps({ direction: 'rtl' })
    expect(wrapper.attributes('data-direction')).toBe('rtl')
  })
})

// ── Interaction test coverage ────────────────────────────────────────────────
// Generated by fill-interaction-gaps.mjs to close health-score gaps.

describe('ShellGrid interactions', () => {
  it('responds to keyboard events', async () => {
    const wrapper = mount(ShellGrid, {
      attachTo: document.body,
    })
    const el = wrapper.find('[tabindex], input, button, [role]')
    const target = el.exists() ? el : wrapper
    await target.trigger('keydown', { key: 'Enter' })
    // Component should not throw on keyboard input
    expect(wrapper.html()).toBeTruthy()
    await target.trigger('keydown', { key: 'Escape' })
    expect(wrapper.html()).toContain('<')
    wrapper.unmount()
  })

  it('can emit events', async () => {
    const wrapper = mount(ShellGrid, {
      attachTo: document.body,
    })
    const clickable = wrapper.find('button, [role="button"], [tabindex], a')
    if (clickable.exists()) {
      await clickable.trigger('click')
    } else {
      await wrapper.trigger('click')
    }
    const events = wrapper.emitted()
    expect(events).toBeDefined()
    wrapper.unmount()
  })

  it('emits update:sizes when sidebar resizer is dragged', async () => {
    const wrapper = mount(ShellGrid, {
      props: { resizable: true, sizes: { sideWidth: 260, panelHeight: 200 } },
    })
    const resizers = wrapper.findAllComponents({ name: 'Resizer' })
    // First resizer is horizontal (sidebar)
    const sideResizer = resizers[0]!
    sideResizer.vm.$emit('dragstart')
    sideResizer.vm.$emit('drag', { delta: 40 })
    await wrapper.vm.$nextTick()
    expect(wrapper.emitted('update:sizes')?.[0]).toEqual([
      { sideWidth: 300, panelHeight: 200 },
    ])
    wrapper.unmount()
  })

  it('clamps sidebar width to 120px minimum', async () => {
    const wrapper = mount(ShellGrid, {
      props: { resizable: true, sizes: { sideWidth: 150, panelHeight: 200 } },
    })
    const resizers = wrapper.findAllComponents({ name: 'Resizer' })
    const sideResizer = resizers[0]!
    sideResizer.vm.$emit('dragstart')
    sideResizer.vm.$emit('drag', { delta: -100 })
    await wrapper.vm.$nextTick()
    expect(wrapper.emitted('update:sizes')?.[0]).toEqual([
      { sideWidth: 120, panelHeight: 200 },
    ])
    wrapper.unmount()
  })

  it('emits update:sizes when panel resizer is dragged', async () => {
    const wrapper = mount(ShellGrid, {
      props: { resizable: true, sizes: { sideWidth: 260, panelHeight: 200 } },
    })
    const resizers = wrapper.findAllComponents({ name: 'Resizer' })
    // Second resizer is vertical (panel)
    const panelResizer = resizers[1]!
    panelResizer.vm.$emit('dragstart')
    // Dragging up = negative delta = larger panel
    panelResizer.vm.$emit('drag', { delta: -50 })
    await wrapper.vm.$nextTick()
    expect(wrapper.emitted('update:sizes')?.[0]).toEqual([
      { sideWidth: 260, panelHeight: 250 },
    ])
    wrapper.unmount()
  })

  it('clamps panel height to 100px minimum', async () => {
    const wrapper = mount(ShellGrid, {
      props: { resizable: true, sizes: { sideWidth: 260, panelHeight: 120 } },
    })
    const resizers = wrapper.findAllComponents({ name: 'Resizer' })
    const panelResizer = resizers[1]!
    panelResizer.vm.$emit('dragstart')
    panelResizer.vm.$emit('drag', { delta: 200 })
    await wrapper.vm.$nextTick()
    expect(wrapper.emitted('update:sizes')?.[0]).toEqual([
      { sideWidth: 260, panelHeight: 100 },
    ])
    wrapper.unmount()
  })

  it('renders titlebar slot when provided', () => {
    const wrapper = mount(ShellGrid, {
      slots: {
        titlebar: '<div id="title">Title</div>',
      },
    })
    expect(wrapper.find('[data-rig-shell-titlebar]').exists()).toBe(true)
    expect(wrapper.find('#title').text()).toBe('Title')
  })

  it('does not render titlebar when slot not provided', () => {
    const wrapper = mount(ShellGrid)
    expect(wrapper.find('[data-rig-shell-titlebar]').exists()).toBe(false)
  })

  it('editor area has role main', () => {
    const wrapper = mount(ShellGrid)
    const editor = wrapper.find('[data-rig-shell-editor]')
    expect(editor.attributes('role')).toBe('main')
    expect(editor.attributes('aria-label')).toBe('Editor')
  })
})

