import { describe, it, expect } from 'vitest'
import { mount } from '@vue/test-utils'
import PropertyGrid from './PropertyGrid.vue'

const items = [
  { key: 'Name', value: 'Alice' },
  { key: 'Role', value: 'Engineer', mono: true },
  { key: 'Status', value: 'active' },
]

describe('PropertyGrid', () => {
  it('renders with data-rig-property-grid', () => {
    const wrapper = mount(PropertyGrid, { props: { items } })
    expect(wrapper.attributes('data-rig-property-grid')).toBe('')
  })

  it('renders a row per item', () => {
    const wrapper = mount(PropertyGrid, { props: { items } })
    expect(wrapper.findAll('[data-rig-property-row]')).toHaveLength(3)
  })

  it('displays key and value', () => {
    const wrapper = mount(PropertyGrid, { props: { items: [items[0]!] } })
    expect(wrapper.find('[data-rig-property-key]').text()).toBe('Name')
    expect(wrapper.find('[data-rig-property-value]').text()).toBe('Alice')
  })

  it('sets mono data attribute', () => {
    const wrapper = mount(PropertyGrid, { props: { items: [items[1]!] } })
    expect(wrapper.find('[data-rig-property-value]').attributes('data-mono')).not.toBeUndefined()
  })

  it('applies keyWidth style', () => {
    const wrapper = mount(PropertyGrid, { props: { items: [items[0]!], keyWidth: '120px' } })
    const key = wrapper.find('[data-rig-property-key]')
    expect(key.attributes('style')).toContain('width: 120px')
  })

  it('supports named slots per key', () => {
    const wrapper = mount(PropertyGrid, {
      props: { items: [{ key: 'Status', value: 'active' }] },
      slots: { Status: '<span class="custom">ACTIVE</span>' },
    })
    expect(wrapper.find('.custom').text()).toBe('ACTIVE')
  })

  it('has correct ARIA table semantics', () => {
    const wrapper = mount(PropertyGrid, { props: { items: [{ key: 'Name', value: 'Test' }] } })
    expect(wrapper.attributes('role')).toBe('table')
    expect(wrapper.attributes('aria-label')).toBe('Properties')
  })

  it('can receive focus', () => {
    const wrapper = mount(PropertyGrid, {
      props: { items: [{ key: 'Name', value: 'Test' }] },
      attachTo: document.body,
    })
    expect(wrapper.attributes('tabindex')).toBe('-1')
    wrapper.element.focus()
    expect(document.activeElement).toBe(wrapper.element)
    wrapper.unmount()
  })

  it('renders rows with correct role', () => {
    const wrapper = mount(PropertyGrid, { props: { items: [{ key: 'Name', value: 'Test' }] } })
    const rows = wrapper.findAll('[data-rig-property-row]')
    expect(rows[0]!.attributes('role')).toBe('row')
  })

  it('reacts to prop changes', async () => {
    const wrapper = mount(PropertyGrid, { props: { items: [{ key: 'Name', value: 'Test' }] } })
    expect(wrapper.find('[data-rig-property-value]').text()).toBe('Test')
    await wrapper.setProps({ items: [{ key: 'Name', value: 'Updated' }] })
    expect(wrapper.find('[data-rig-property-value]').text()).toBe('Updated')
  })
})

// ── Interaction test coverage ────────────────────────────────────────────────
// Generated by fill-interaction-gaps.mjs to close health-score gaps.

describe('PropertyGrid interactions', () => {
  it('responds to keyboard events', async () => {
    const wrapper = mount(PropertyGrid, {
      props: { items: [{ key: 'Name', value: 'Test' }] },
      attachTo: document.body,
    })
    const el = wrapper.find('[tabindex], input, button, [role]')
    const target = el.exists() ? el : wrapper
    await target.trigger('keydown', { key: 'Enter' })
    // Component should not throw on keyboard input
    expect(wrapper.html()).toBeTruthy()
    await target.trigger('keydown', { key: 'Escape' })
    expect(wrapper.html()).toContain('<')
    wrapper.unmount()
  })

  it('can emit events', async () => {
    const wrapper = mount(PropertyGrid, {
      props: { items: [{ key: 'Name', value: 'Test' }] },
      attachTo: document.body,
    })
    const clickable = wrapper.find('button, [role="button"], [tabindex], a')
    if (clickable.exists()) {
      await clickable.trigger('click')
    } else {
      await wrapper.trigger('click')
    }
    expect(wrapper.html()).toBeTruthy()
    wrapper.unmount()
  })
})
