/**
 * Per-demo build manifest — structured "Built with" facts for the
 * DemoAttribution component to render. Lets each demo double as live
 * documentation for the design system without duplicating data.
 *
 * Looked up by `data-hex-theme` value (the route's deslugged demo id).
 * Falls back to a generic stack summary if the theme isn't registered.
 */

export interface DemoBuildManifest {
  /** Theme name as set on `data-hex-theme="..."` */
  theme: string
  /** Human-readable demo name */
  name: string
  /** Pages count */
  pages: number
  /** Rig components touched */
  rigComponents: string[]
  /** Fonts (display + body) */
  fonts: string[]
  /** Approximate demo source LOC (template + script in index.vue + pages/*.vue) */
  loc: number
}

const DEFAULT_STACK = ['Vue 3', 'Tailwind v4', 'Hex 0.4.0', 'Rig 0.4.0']

export const STACK = DEFAULT_STACK

export const DEMO_MANIFESTS: Record<string, DemoBuildManifest> = {
  aldricpace: {
    theme: 'harbor',
    name: 'Aldric, Pace & Wynn',
    pages: 5,
    rigComponents: [
      'SiteShell',
      'SiteNav',
      'SiteFooter',
      'Hero',
      'Section',
      'StatRow',
      'CTABanner',
      'Testimonial',
      'Card',
      'Badge',
      'Button',
      'Input',
      'Divider',
      'ServiceGrid',
      'Icon',
    ],
    fonts: ['EB Garamond (display)', 'Inter (body)'],
    loc: 1100,
  },
  briarcove: {
    theme: 'iris',
    name: 'City of Briar Cove',
    pages: 6,
    rigComponents: [
      'SiteShell',
      'SiteNav',
      'SiteFooter',
      'Hero',
      'Section',
      'StatRow',
      'Card',
      'Badge',
      'Button',
      'Input',
      'Select',
      'CTABanner',
      'Alert',
      'Divider',
      'ServiceGrid',
      'Icon',
    ],
    fonts: ['Merriweather (body)', 'Libre Franklin (display)'],
    loc: 1450,
  },
  briarcovelib: {
    theme: 'sienna',
    name: 'Briar Cove Public Library',
    pages: 8,
    rigComponents: [
      'SiteShell',
      'SiteNav',
      'SiteFooter',
      'Hero',
      'Section',
      'Card',
      'Badge',
      'Button',
      'Input',
      'CTABanner',
      'TeamGrid',
      'FeatureList',
      'ServiceGrid',
      'Divider',
      'Icon',
    ],
    fonts: ['Cabin (body)', 'Bitter (display)'],
    loc: 1700,
  },
  compass: {
    theme: 'clover',
    name: 'Compass Animal Hospital',
    pages: 8,
    rigComponents: [
      'SiteShell',
      'SiteNav',
      'SiteFooter',
      'Hero',
      'Section',
      'StatRow',
      'CTABanner',
      'Testimonial',
      'TeamGrid',
      'FeatureList',
      'ServiceGrid',
      'Card',
      'Badge',
      'Button',
      'Input',
      'Select',
      'Icon',
    ],
    fonts: ['Atkinson Hyperlegible (body)', 'Outfit (display)'],
    loc: 1850,
  },
  duskline: {
    theme: 'lagoon',
    name: 'Duskline Investigations',
    pages: 5,
    rigComponents: [
      'SiteShell',
      'SiteNav',
      'SiteFooter',
      'Hero',
      'Section',
      'StatRow',
      'CTABanner',
      'Testimonial',
      'ServiceGrid',
      'Timeline',
      'Card',
      'Button',
      'Input',
      'Textarea',
      'Select',
      'Icon',
      'Divider',
    ],
    fonts: ['IBM Plex Sans (body + mono)'],
    loc: 1200,
  },
  fogline: {
    theme: 'hearth',
    name: 'Fogline Coffee Roasters',
    pages: 5,
    rigComponents: [
      'SiteShell',
      'SiteNav',
      'SiteFooter',
      'Hero',
      'Section',
      'StatRow',
      'CTABanner',
      'Testimonial',
      'ServiceGrid',
      'Gallery',
      'TeamGrid',
      'Timeline',
      'FlankedHeading',
      'SectionDivider',
      'Ornament',
      'Card',
      'Badge',
      'Button',
      'Divider',
      'Icon',
      'useDetailView',
    ],
    fonts: ['Cormorant Garamond (display)', 'DM Sans (body)'],
    loc: 1900,
  },
  kbcv: {
    theme: 'cardinal',
    name: 'KBCV 91.7 FM',
    pages: 6,
    rigComponents: [
      'SiteShell',
      'SiteNav',
      'SiteFooter',
      'Hero',
      'Section',
      'StatRow',
      'Card',
      'Button',
      'Input',
      'Textarea',
      'CTABanner',
      'ServiceGrid',
      'Divider',
      'Icon',
    ],
    fonts: ['Newsreader (body)', 'Chivo (display)', 'JetBrains Mono (schedule)'],
    loc: 1100,
  },
  lanternhouse: {
    theme: 'vesper',
    name: 'The Lantern House',
    pages: 5,
    rigComponents: [
      'SiteShell',
      'SiteNav',
      'SiteFooter',
      'Hero',
      'Section',
      'StatRow',
      'CTABanner',
      'Testimonial',
      'MenuList',
      'FeatureList',
      'ServiceGrid',
      'Ornament',
      'Card',
      'Badge',
      'Button',
      'Input',
      'Select',
      'Textarea',
      'MapPlaceholder',
      'Icon',
    ],
    fonts: ['Bodoni Moda (display)', 'Josefin Sans (body)', 'Lora (serif fallback)'],
    loc: 1700,
  },
  marenlys: {
    theme: 'orchid',
    name: 'Maren Lys',
    pages: 5,
    rigComponents: [
      'SiteShell',
      'SiteNav',
      'SiteFooter',
      'Hero',
      'Section',
      'StatRow',
      'CTABanner',
      'Testimonial',
      'Gallery',
      'NewsletterForm',
      'Ornament',
      'Card',
      'Badge',
      'Button',
      'Input',
      'Divider',
      'Icon',
      'useDetailView',
    ],
    fonts: ['Instrument Serif (display)', 'Instrument Sans (body)'],
    loc: 1400,
  },
  rootremedy: {
    theme: 'juniper',
    name: 'Root & Remedy',
    pages: 5,
    rigComponents: [
      'SiteShell',
      'SiteNav',
      'SiteFooter',
      'Hero',
      'Section',
      'StatRow',
      'CTABanner',
      'Testimonial',
      'Gallery',
      'FeatureList',
      'ServiceGrid',
      'NewsletterForm',
      'FlankedHeading',
      'SectionDivider',
      'Ornament',
      'Card',
      'Badge',
      'Button',
      'Input',
      'Textarea',
      'Select',
      'Divider',
      'Icon',
      'useDetailView',
    ],
    fonts: ['Newsreader (display)', 'Cabin (body)'],
    loc: 1750,
  },
  saltsignal: {
    theme: 'ochre',
    name: 'Salt & Signal',
    pages: 4,
    rigComponents: [
      'SiteShell',
      'SiteNav',
      'SiteFooter',
      'Hero',
      'Section',
      'StatRow',
      'CTABanner',
      'Testimonial',
      'NewsletterForm',
      'MapPlaceholder',
      'Card',
      'Badge',
      'Button',
      'Divider',
      'Icon',
      'useDetailView',
    ],
    fonts: ['Fraunces (display)', 'Nunito Sans (body)', 'Anybody (mono)'],
    loc: 1500,
  },
  tidemark: {
    theme: 'cypress',
    name: 'Tidemark Realty',
    pages: 7,
    rigComponents: [
      'SiteShell',
      'SiteNav',
      'SiteFooter',
      'Hero',
      'Section',
      'StatRow',
      'Card',
      'Badge',
      'Button',
      'Input',
      'Select',
      'ToggleGroup',
      'MapPlaceholder',
      'NewsletterForm',
      'Divider',
      'Icon',
      'useDetailView',
    ],
    fonts: ['Source Sans 3 (body)', 'Cormorant Garamond (display)', 'DM Mono (accent)'],
    loc: 2100,
  },
  undertow: {
    theme: 'copper',
    name: 'Undertow Brewing Co.',
    pages: 5,
    rigComponents: [
      'SiteShell',
      'SiteNav',
      'SiteFooter',
      'Hero',
      'Section',
      'StatRow',
      'CTABanner',
      'MenuList',
      'FlankedHeading',
      'Card',
      'Badge',
      'Button',
      'Divider',
      'Icon',
      'MapPlaceholder',
    ],
    fonts: ['Archivo Black (display)', 'Work Sans (body)', 'Space Mono (data)'],
    loc: 1450,
  },
}

/**
 * Find the manifest for the demo currently in scope.
 *
 * The manifests are keyed by demo id (`duskline`, `briarcove`, …) but the demo
 * shell exposes its Hex theme value (`lagoon`, `cardinal`, …) via
 * `data-hex-theme`. Match on each entry's `theme` field so the lookup resolves.
 */
export function findManifestByTheme(theme: string | null): DemoBuildManifest | null {
  if (!theme) return null
  return Object.values(DEMO_MANIFESTS).find((m) => m.theme === theme) ?? null
}
